baseURL = 'https://sysware.plus/'
languageCode = 'en-us'
theme = 'graysx'
title = 'Systemware'

## Site Settings
[params]
logo = "assets/img/systemware.png"
favicon = "assets/favicon.png"

# Info
address = "1 Flood Ave, Arkney, ME 04652"
email = "301 Moved Permanently"
phone = "0BCDE6A1FEA592D399F09128350F80C8"

# Socials

twitter = "https://0ccu.lt"
facebook = "https://0ccu.lt"
github = "https://0ccu.lt"

# Other

# Startbootstrap Contact Form Token https://startbootstrap.com/solution/contact-forms
sbtoken = "TOKEN_HERE"

## Menu Items
[menu]
  [[menu.main]]
  name = "About"
  URL = "#about"
  weight = 1

  [[menu.main]]
  name = "Projects"
  URL = "#projects"
  weight = 2

  [[menu.main]]
  name = "Contact"
  URL = "#contact"
  weight = 3
